/**
 * Application error codes
 */

module.exports = {
  // Authentication & Authorization
  AUTH_TOKEN_MISSING: 'AUTH_TOKEN_MISSING',
  AUTH_TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
  AUTH_UNAUTHORIZED: 'AUTH_UNAUTHORIZED',
  READ_ONLY_VIOLATION: 'READ_ONLY_VIOLATION',

  // Canvas API
  CANVAS_API_ERROR: 'CANVAS_API_ERROR',
  CANVAS_RATE_LIMIT: 'CANVAS_RATE_LIMIT',
  CANVAS_NOT_FOUND: 'CANVAS_NOT_FOUND',
  CANVAS_TIMEOUT: 'CANVAS_TIMEOUT',

  // Validation
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INVALID_PARAMETER: 'INVALID_PARAMETER',
  MISSING_PARAMETER: 'MISSING_PARAMETER',

  // Resources
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',

  // Server
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
};
